######################################################################
# Automatically generated by qmake (3.0) ?? ???. 8 20:45:30 2017
######################################################################

TEMPLATE    = app
TARGET      = dchallenge

android {
    QT      += qml quick
    SOURCES += src/Android.cpp
} else {
    QT      += widgets
    FORMS   += ui/DChallenge.ui
    SOURCES += src/Main.cpp
}
CONFIG      += c++11
INCLUDEPATH += .
RESOURCES   += qml.qrc

# Input
