######################################################################
# Automatically generated by qmake (3.0) ?? ???. 8 20:45:30 2017
######################################################################

QT += widgets
TEMPLATE = app
TARGET = dchallenge
INCLUDEPATH += .

# Input
SOURCES += src/Main.cpp
FORMS += ui/DChallenge.ui
